# Generated by Django 5.2.12 on 2026-04-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mob', models.CharField(max_length=50, verbose_name='mobile')),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
